name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag simple-docker-project:${{ env.GITHUB_SHA }}
    - name: Push To Registry
      uses: redhat-actions/push-to-registry@v2.5.1
      with:
        image: simple-docker-project
        tags: ${{ env.GITHUB_SHA }}
        registry: quay.io/dustin_codefresh
        username: dev@vanbuskirk.me
        password: ${{ secrets.QUAY_PASSWORD }}
