name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag simple-docker-project:${{ github.sha }}

    - name: Push To Registry
      uses: redhat-actions/push-to-registry@v2.5.1
      with:
        image: simple-docker-project
        tags: ${{ github.sha }}
        registry: dustinvanbuskirk
        username: dustinvanbuskirk
        password: ${{ secrets.docker_hub_password }}
    - name: Report Image To CSDP
      uses: docker://quay.io/codefreshplugins/argo-hub-workflows-codefresh-csdp-versions-0.0.6-images-report-image-info:main
      with:
        entrypoint: node /index.js
      env:
        IMAGE_URI: docker.io/dustinvanbuskirk/simple-docker-project:${{ github.sha }}
        CF_API_KEY: ${{ secrets.csdp_api_key }}
        GIT_BRANCH: ${{ github.ref.name }}
        GIT_REVISION: ${{ github.sha }}
        GIT_COMMIT_MESSAGE: GitHub Actions have been here
        GIT_COMMIT_URL: ${{ github.server.url }}/${{ github.repository }}/actions/runs/${{ github.run.id }}
        DOCKER_USERNAME: dustinvanbuskirk
        DOCKER_PASSWORD: ${{ secrets.docker_hub_password }}
        WORKFLOW_NAME: ${{ github.workflow }}
        GIT_SENDER_LOGIN: ${{ github.actor }}
        CF_HOST: https://g.codefresh.io
